# FILE: tests/server/test_auth_go_compat.py
# VERSION: 1.0.0
# START_MODULE_CONTRACT:
# PURPOSE: Go-compatibility fixture verifier for src/server/auth.py. Loads tokens
#          generated by Go kernel/sessiontoken/token.go Issue() (via Go runtime) from
#          tests/server/fixtures/go_generated_tokens.json and verifies that the Python
#          verify_session_token() produces the expected outcome for each entry.
#          This is the cryptographic parity regression test (plan §5.3, §2.1 exit criteria).
# SCOPE: Go wire-format compat; fixture-driven parametrised tests; freezegun time control.
# INPUT: tests/server/fixtures/go_generated_tokens.json (generated by Go runtime).
# OUTPUT: pytest PASS/FAIL per fixture entry with LDD telemetry.
# KEYWORDS: [DOMAIN(10): GoCompatParity; CONCEPT(10): WireFormatParity;
#            PATTERN(9): ParametrisedFixture; TECH(9): freezegun; CONCEPT(8): RegressionTest]
# LINKS: [READS_DATA_FROM(10): tests/server/fixtures/go_generated_tokens.json;
#         READS_DATA_FROM(10): src/server/auth.py;
#         READS_DATA_FROM(9): crablink-gateway/kernel/sessiontoken/token.go]
# LINKS_TO_SPECIFICATION: DevelopmentPlan_MCP.md §2.1 exit criteria (Go-compat fixture test),
#   §5.3 (fixture format), TASK_brainstorm_mcp_integration.md §7.1
# END_MODULE_CONTRACT
#
# START_INVARIANTS:
# - Fixture file must exist and be parseable JSON.
# - All "ok" entries must verify without error using fixed_now = fixture _base_now.
# - All "bad_signature" entries must raise AuthError("bad_signature").
# - All "expired" entries must raise AuthError("expired") when verified at _base_now.
# - _generator field in JSON documents the Go source that produced the tokens.
# END_INVARIANTS
#
# START_RATIONALE:
# Q: Why use freezegun instead of passing fixed_now directly?
# A: freezegun.freeze_time patches time.time() globally, which is what we call internally
#    via int(time.time()) in require_service deps. For direct verify_session_token calls
#    we pass now= explicitly, so freezegun is only used for the Depends path tests.
#    For direct function tests, we pass fixed_now fixture directly.
# Q: Why parametrise over fixture entries rather than hard-coding individual test functions?
# A: The fixture file is the source of truth for Go compat. Adding new tokens to the
#    JSON automatically adds new test cases. This makes the regression set extensible
#    without touching test code.
# END_RATIONALE
#
# START_CHANGE_SUMMARY:
# LAST_CHANGE: [v1.0.0 - Initial creation as Slice A: Go-compat fixture verifier.]
# END_CHANGE_SUMMARY

import json
import logging
from pathlib import Path

import pytest
from freezegun import freeze_time

from src.server.auth import AuthError, TokenClaims, verify_session_token

# Path to the Go-generated fixture file
_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "go_generated_tokens.json"


# START_FUNCTION__load_fixture
# START_CONTRACT:
# PURPOSE: Load and return the fixture data from go_generated_tokens.json.
#          Raises FileNotFoundError if fixture is missing (must be committed).
# OUTPUTS:
#   - dict: Full fixture JSON including _base_now, _future_exp, entries list
# KEYWORDS: [PATTERN(7): FixtureLoader]
# COMPLEXITY_SCORE: 2
# END_CONTRACT
def _load_fixture() -> dict:
    """
    Load the Go-generated token fixture from disk. The fixture must be committed to the
    repository. If missing, the test session fails with a clear FileNotFoundError message.
    The _generator field in the JSON documents the Go code used to produce the tokens.
    """
    if not _FIXTURE_PATH.exists():
        raise FileNotFoundError(
            f"Go-compat fixture not found at {_FIXTURE_PATH}. "
            f"Run the Go generator script to (re)create it: "
            f"'go run /tmp/gen_tokens.go > {_FIXTURE_PATH}'"
        )
    with open(_FIXTURE_PATH) as f:
        return json.load(f)
# END_FUNCTION__load_fixture


# Load fixture once at module level for parametrisation
_FIXTURE_DATA = _load_fixture()
_BASE_NOW: int = _FIXTURE_DATA["_base_now"]
_ENTRIES: list = _FIXTURE_DATA["entries"]
_SECRET_HEX: str = _ENTRIES[0]["secret_hex"]  # All entries use the same secret
_SECRET_BYTES: bytes = bytes.fromhex(_SECRET_HEX)


# START_FUNCTION_test_fixture_file_exists_and_is_valid
# START_CONTRACT:
# PURPOSE: Verify the fixture file exists, is valid JSON, and has the required structure.
#          This is a smoke test before the parametrised tests run.
# KEYWORDS: [CONCEPT(8): FixtureSanity; PATTERN(7): SmokeTest]
# COMPLEXITY_SCORE: 2
# END_CONTRACT
def test_fixture_file_exists_and_is_valid():
    """
    Smoke: fixture file exists, is valid JSON, contains required metadata fields
    and the expected number of entries (6 minimum per plan §5.3).
    """
    assert _FIXTURE_PATH.exists(), f"Fixture file missing: {_FIXTURE_PATH}"

    data = _load_fixture()

    assert "_generator" in data, "Fixture must have _generator field documenting Go source"
    assert "_base_now" in data, "Fixture must have _base_now field"
    assert "_future_exp" in data, "Fixture must have _future_exp field"
    assert "entries" in data, "Fixture must have entries list"

    entries = data["entries"]
    assert len(entries) >= 6, f"Fixture must have at least 6 entries, got {len(entries)}"

    # Count categories
    outcomes = [e["expected_outcome"] for e in entries]
    ok_count = outcomes.count("ok")
    bad_sig_count = outcomes.count("bad_signature")
    expired_count = outcomes.count("expired")

    assert ok_count >= 3, f"Need at least 3 positive ('ok') entries, got {ok_count}"
    assert bad_sig_count >= 2, f"Need at least 2 bad_signature entries, got {bad_sig_count}"
    assert expired_count >= 1, f"Need at least 1 expired entry, got {expired_count}"
# END_FUNCTION_test_fixture_file_exists_and_is_valid


# START_FUNCTION_test_go_generated_token_positive
# START_CONTRACT:
# PURPOSE: Each "ok" fixture entry must verify successfully when time is frozen at base_now.
#          Returns correct TokenClaims with service_id="brainstorm" and matching session_id.
# KEYWORDS: [CONCEPT(10): GoCompatHappyPath; PATTERN(9): ParametrisedTest; TECH(8): freezegun]
# COMPLEXITY_SCORE: 5
# END_CONTRACT
@pytest.mark.parametrize(
    "entry",
    [e for e in _ENTRIES if e["expected_outcome"] == "ok"],
    ids=[e["label"] for e in _ENTRIES if e["expected_outcome"] == "ok"],
)
def test_go_generated_token_positive(entry, ldd_capture, caplog):
    """
    Each Go-generated positive token must verify successfully.
    Time is frozen at _base_now so that exp = base_now + 3600 is still in the future.
    Verifies byte-for-byte HMAC parity between Go Issue() and Python verify_session_token().
    """
    caplog.set_level(logging.DEBUG)

    bearer = entry["token"]
    decoded = entry["decoded_payload"]

    # Use _BASE_NOW as the 'now' parameter: tokens expire at base_now+3600, so exp > now
    claims = verify_session_token(
        raw_authorization_header=bearer,
        required_service_id="brainstorm",
        now=_BASE_NOW,
        secret=_SECRET_BYTES,
    )

    # START_BLOCK_LDD_TELEMETRY: [Print IMP:7-10 BEFORE assertions]
    high_imp_logs = ldd_capture()
    # END_BLOCK_LDD_TELEMETRY

    # START_BLOCK_VERIFICATION: [Assert claims match Go fixture]
    assert isinstance(claims, TokenClaims)
    assert claims.service_id == decoded["service_id"], (
        f"service_id mismatch: got {claims.service_id}, want {decoded['service_id']}"
    )
    assert claims.session_id == decoded["session_id"], (
        f"session_id mismatch: got {claims.session_id}, want {decoded['session_id']}"
    )
    assert claims.exp == decoded["exp"], (
        f"exp mismatch: got {claims.exp}, want {decoded['exp']}"
    )

    # I6: user_id must not be in TokenClaims
    assert not hasattr(claims, "user_id"), "I6 VIOLATION: user_id found in claims from Go token"

    # Anti-Illusion: IMP:9 BELIEF log must be present
    found_belief = any("[Verify-OK][BELIEF]" in log for log in high_imp_logs)
    assert found_belief, (
        f"LDD Error: IMP:9 [Auth][Verify-OK][BELIEF] not found for Go fixture entry '{entry['label']}'"
    )
    # END_BLOCK_VERIFICATION
# END_FUNCTION_test_go_generated_token_positive


# START_FUNCTION_test_go_generated_token_bad_signature
# START_CONTRACT:
# PURPOSE: Each "bad_signature" fixture entry must raise AuthError("bad_signature").
#          Covers tampered sig and truncated payload cases.
# KEYWORDS: [CONCEPT(9): GoCompatBadSig; PATTERN(8): ParametrisedTest]
# COMPLEXITY_SCORE: 3
# END_CONTRACT
@pytest.mark.parametrize(
    "entry",
    [e for e in _ENTRIES if e["expected_outcome"] == "bad_signature"],
    ids=[e["label"] for e in _ENTRIES if e["expected_outcome"] == "bad_signature"],
)
def test_go_generated_token_bad_signature(entry, ldd_capture, caplog):
    """
    Go-generated tokens with tampered signature or truncated payload must raise
    AuthError('bad_signature'). LDD IMP:9 [Verify-Failed] must be logged.
    """
    caplog.set_level(logging.DEBUG)

    bearer = entry["token"]

    with pytest.raises(AuthError) as exc_info:
        verify_session_token(
            raw_authorization_header=bearer,
            required_service_id="brainstorm",
            now=_BASE_NOW,
            secret=_SECRET_BYTES,
        )

    # START_BLOCK_LDD_TELEMETRY
    high_imp_logs = ldd_capture()
    # END_BLOCK_LDD_TELEMETRY

    assert exc_info.value.reason in ("bad_signature", "malformed"), (
        f"Tampered token '{entry['label']}' should raise bad_signature or malformed, "
        f"got '{exc_info.value.reason}'"
    )

    # Anti-Illusion: IMP:9 [Verify-Failed] must be logged
    found_fail = any("[Verify-Failed]" in log for log in high_imp_logs)
    assert found_fail, (
        f"LDD Error: IMP:9 [Verify-Failed] not logged for bad fixture entry '{entry['label']}'"
    )
# END_FUNCTION_test_go_generated_token_bad_signature


# START_FUNCTION_test_go_generated_token_expired
# START_CONTRACT:
# PURPOSE: Each "expired" fixture entry must raise AuthError("expired") when verified
#          at _BASE_NOW (the expired token's exp is base_now - 3600).
# KEYWORDS: [CONCEPT(9): GoCompatExpiry; PATTERN(8): ParametrisedTest]
# COMPLEXITY_SCORE: 3
# END_CONTRACT
@pytest.mark.parametrize(
    "entry",
    [e for e in _ENTRIES if e["expected_outcome"] == "expired"],
    ids=[e["label"] for e in _ENTRIES if e["expected_outcome"] == "expired"],
)
def test_go_generated_token_expired(entry, ldd_capture, caplog):
    """
    Go-generated expired tokens must raise AuthError('expired') when verified at _BASE_NOW.
    The expired token's exp = base_now - 3600 which is < _BASE_NOW.
    """
    caplog.set_level(logging.DEBUG)

    bearer = entry["token"]

    with pytest.raises(AuthError) as exc_info:
        verify_session_token(
            raw_authorization_header=bearer,
            required_service_id="brainstorm",
            now=_BASE_NOW,
            secret=_SECRET_BYTES,
        )

    # START_BLOCK_LDD_TELEMETRY
    high_imp_logs = ldd_capture()
    # END_BLOCK_LDD_TELEMETRY

    assert exc_info.value.reason == "expired", (
        f"Expired token '{entry['label']}' should raise 'expired', got '{exc_info.value.reason}'"
    )

    found_fail = any("[Verify-Failed]" in log for log in high_imp_logs)
    assert found_fail, (
        f"LDD Error: IMP:9 [Verify-Failed] not logged for expired fixture entry '{entry['label']}'"
    )
# END_FUNCTION_test_go_generated_token_expired


# START_FUNCTION_test_all_fixture_entries_are_covered
# START_CONTRACT:
# PURPOSE: Verify that all entries in the fixture file are covered by the parametrised
#          tests above. No fixture entry should have an unknown expected_outcome.
# KEYWORDS: [CONCEPT(7): FixtureCoverage; PATTERN(6): ExhaustivenessCheck]
# COMPLEXITY_SCORE: 2
# END_CONTRACT
def test_all_fixture_entries_are_covered():
    """
    Every fixture entry must have an expected_outcome of "ok", "bad_signature", or "expired".
    Unknown outcomes indicate a fixture generation error and must fail loudly.
    """
    known_outcomes = {"ok", "bad_signature", "expired"}
    for entry in _ENTRIES:
        outcome = entry.get("expected_outcome", "MISSING")
        assert outcome in known_outcomes, (
            f"Fixture entry '{entry.get('label', '?')}' has unknown expected_outcome '{outcome}'. "
            f"Valid values: {known_outcomes}"
        )
# END_FUNCTION_test_all_fixture_entries_are_covered


# START_FUNCTION_test_go_compat_secret_consistency
# START_CONTRACT:
# PURPOSE: All fixture entries must use the same secret (consistent fixture).
# KEYWORDS: [CONCEPT(7): FixtureSanity]
# COMPLEXITY_SCORE: 1
# END_CONTRACT
def test_go_compat_secret_consistency():
    """All fixture entries must reference the same HMAC secret for consistency."""
    first_secret = _ENTRIES[0]["secret_hex"]
    for entry in _ENTRIES:
        assert entry["secret_hex"] == first_secret, (
            f"Entry '{entry['label']}' has different secret_hex. "
            f"All entries must use the same secret for fixture consistency."
        )
# END_FUNCTION_test_go_compat_secret_consistency
